trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: github-sync-secrets # Grupo con GH_PAT

steps:
  - checkout: self
    fetchDepth: 0

  - script: |
      git config --global user.email "ci-bot@intelligentnutrition.shop"
      git config --global user.name "CI-CD Bot"

      git remote add deploy "https://github.com/fredylopez01/intelligent-nutrition.git"

      git checkout -B main

      AUTH_HEADER="AUTHORIZATION: basic $(echo -n x-access-token:$GH_PAT | base64 -w0)"
      git -c http.https://github.com/.extraheader="$AUTH_HEADER" push deploy main --force
    displayName: "Sync main branch to GitHub"
    env:
      GH_PAT: $(GH_PAT)