# azure-pipelines.yml
# Sincroniza la rama main de Azure Repos hacia GitHub

trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: github-sync-secrets # Grupo con GH_PAT

steps:
  - checkout: self
    fetchDepth: 0

  - script: |
      git config --global user.email "ci-bot@intelligentnutrition.shop"
      git config --global user.name "CI-CD Bot"

      # Usar "deploy" como nombre del remoto, sin tocar "origin"
      git remote add deploy "https://$GH_PAT@github.com/fredylopez01/intelligent-nutrition.git"

      # Renombrar la rama actual (detached HEAD) a main
      git branch -M main

      # Push hacia GitHub
      git push -u deploy main --force
    displayName: "Sync main branch to GitHub"
    env:
      GH_PAT: $(GH_PAT)
