FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY prisma ./prisma
COPY prisma.config.ts ./
COPY tsconfig*.json ./
COPY nest-cli.json ./
COPY jest.config.ts ./
COPY src ./src

RUN npx prisma generate

CMD ["node", "--experimental-vm-modules", "node_modules/jest/bin/jest.js", "--config", "jest.config.ts", "--verbose"]